#pragma once

#include "emu/utility/dynamic_array.h"
#include "emu/utility/spsc_ring_buffer.h"

#include <SFML/Audio.hpp>

#include <atomic>
#include <concepts>
#include <cstddef>
#include <limits>
#include <span>

namespace emu::app {

/**
 * Streamed audio source that plays audio samples generated by the emulator.
 */
class audio_stream : public sf::SoundStream {
public:
    using value_type = sf::Int16;
    static constexpr std::size_t block_size = 128;

public:
    /** Creates a mono audio stream with the given sample rate. */
    explicit audio_stream(unsigned int sample_rate);

public:
    /** Pushes a block into the internal FIFO. Blocks until enough space becomes available. */
    void push(std::span<value_type const> values);

    /** Waits until the FIFO has been prefilled enough for playback to start. */
    void wait_until_prefilled();

private:
    /** Requests a new chunk of audio samples from the stream source. */
    bool onGetData(sf::SoundStream::Chunk& data) override;

    /** Changes the current playing position in the stream source. */
    void onSeek(sf::Time) override;

private:
    static constexpr std::size_t samples_size = 4 * block_size;
    static constexpr std::size_t buffer_size  = 4 * samples_size;

    emu::spsc_ring_buffer<value_type>       my_fifo;
    dynamic_array<value_type, samples_size> my_samples;

    std::atomic<unsigned long long> my_drain_seq = 0;
};

/////////////////////////////////////////////////////////////////////////

/** Linearly maps a value from [0, 1] to the integral range [-M, M], where M = max(T). */
template<std::signed_integral T>
T to_pcm_sample(double value) noexcept {
    constexpr T max = std::numeric_limits<T>::max();
    return static_cast<T>(max * (2 * value - 1));
}

} // namespace emu::app
